# MySQL Database Configuration (Docker)
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/aircraft_instrumentation_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
